# .github/workflows/dotnet-ci.yml
name: .NET CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore --nologo

      # Make sure your test project references coverlet.collector:
      # dotnet add Shapes.Tests package coverlet.collector
      - name: Test with coverage
        run: dotnet test --no-build -c Release --collect:"XPlat Code Coverage" --nologo --verbosity minimal

      # (Optional) debug: show where the XML landed
      - name: Locate coverage files (debug)
        run: |
          echo "Searching for coverage.cobertura.xml..."
          find . -name "coverage.cobertura.xml" -print

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Generate HTML coverage report
        run: ~/.dotnet/tools/reportgenerator -reports:"**/TestResults/*/coverage.cobertura.xml" -targetdir:"coveragereport" -reporttypes:"Html;TextSummary"

      # 👇 Upload BOTH the XML and the HTML folder
      - name: Upload coverage (XML + HTML)
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            **/TestResults/*/coverage.cobertura.xml
            coveragereport/**
