# .github/workflows/dotnet-ci.yml
name: .NET CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet restore
      - run: dotnet build --configuration Release --nologo
      - run: dotnet test --configuration Release --nologo --verbosity minimal
      - run: dotnet test --no-build -c Release --collect:"XPlat Code Coverage"
      - name: Locate coverage files (debug)
        run: |
          echo "Searching for coverage.cobertura.xml..."
          find . -name "coverage.cobertura.xml" -print
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            **/TestResults/*/coverage.cobertura.xml
